### ISSUE TITLE
$insert->raw not present

### ISSUE THREAD

**Issue by tolgaulas** [atlasphp/Atlas.Statement#1]
Despite the documentation says https://github.com/atlasphp/Atlas.Statement/blob/7d7dc93efa90a5f76f7a4efedbddba42362e0483/docs/insert.md?plain=1#L52

$insert->raw() method is not to be found.

**Comment by harikt** [comment]
I think you want to use `set` method. https://github.com/atlasphp/Atlas.Statement/blob/7d7dc93efa90a5f76f7a4efedbddba42362e0483/src/Clause/ModifyColumns.php#L36 .

**Comment by tolgaulas** [comment]
yes, i used it instead; may be the doc should be updated.
